version: '3'
services:
  tnn:
    build:
     context: ./tnn/
     args:
      pwsysop: 12345678901234567890123456789012345678901234567890123456789012345678901234567890
      pwconsole: admin
      nodeident: DIGFTL
      nodecall: FT1NOD
      location: Freital, SAX, DE
      locator: JO61TA
      port1: AX25IP|AX25IP|8|19200d
    ports:
     - 10093:10093/udp
    volumes:
     - ./conf/tnn/:/cfg
    restart: unless-stopped
  openbcm:
    build:
     context: ./openbcm/
     args:
      boxaddr: FT1BOX.#DD.SAX.DEU.EU
      mycall: FT1BOX
      sysop: PE1FTL
    ports:
     - 8081:8080
    volumes:
     - ./conf/openbcm/:/cfg
